spring.application.name=cart-service
#database configuration
spring.datasource.url= jdbc:postgresql://localhost:5432/cart_service
spring.datasource.username=postgres
spring.datasource.password=0742257435
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=8080

spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.product.product_service=DEBUG